Fix a :exc:`RuntimeWarning` when calling ``agen.aclose().throw(Exception)``.
